CREATE TABLE `supercookie_data`(
`id` int (20) unsigned NOT NULL AUTO_INCREMENT,
`userData` int(20) DEFAULT NULL,
`cookieData` int(20) DEFAULT NULL,
`localData` int(20) DEFAULT NULL,
`globalData` int(20) DEFAULT NULL,
`sessionData` int(20) DEFAULT NULL,
`windowData` int(20) DEFAULT NULL,
`historyData` int(20) DEFAULT NULL,
`pngData` int(20) DEFAULT NULL,
`etagData` int(20) DEFAULT NULL,
`cacheData` int(20) DEFAULT NULL,
`idbData` int(20) DEFAULT NULL,
`dbData` int(20) DEFAULT NULL,
`lsoData` int(20) DEFAULT NULL,
`slData` int(20) DEFAULT NULL,
)
